### ISSUE TITLE
Добавления токена авторизации

### ISSUE THREAD

**Issue by SmirnovVadV** [kolesnikovm/jmeter-prometheus-listener#3]
Добрый день, Спасибо за вашу работу!
Очень хотели бы использовать вашу версию listener`a.
Есть ли возможность добавления в значения параметров, строки для авторизации по токену, как пример: 
Authorization: Bearer \<token\>?

**Comment by kolesnikovm** [comment]
Добрый день, как именно хотите использовать процесс авторизации?
Добавить в таргет прометея? Как конфигурировать секреты?
